name: Java with Nexus Repository

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        projectKey: develop
        projectName: 'develop'
        sonarUrl: http://43.204.38.164:9000
        token: sqp_83d9f2c92591c4b36edde5d15f6d05c9f6ac9ccb
      env:
        SONAR_TOKEN: sqp_83d9f2c92591c4b36edde5d15f6d05c9f6ac9ccb
        SONAR_HOST_URL: http://43.204.38.164:9000
    # Check the Quality Gate status.
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
      timeout-minutes: 5
      env:
       SONAR_TOKEN: sqp_83d9f2c92591c4b36edde5d15f6d05c9f6ac9ccb
       SONAR_HOST_URL: http://43.204.38.164:9000
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://3.110.83.6:8081
        username: admin
        password: admin
        format: maven2
        repository: maven-releases
        coordinates: groupId=com.example artifactId=student-task-tracker version=1.0.2
        assets: extension=war
        filename: ./target/student-task-tracker.war
